### ISSUE TITLE
Only first 10k players taken

### ISSUE THREAD

**Issue by Ntonio36** [kafagy95/fifa18-Data#3]
The database is about nearly 15k players wide, and the main players page only shows the "first 10 thousand players". A fix for it could be separately dumping bronze, then silver, then gold players. As no quality exceeds 10k players, taking them all should be seamless.

**Comment by kafagy** [comment]
Hi @Ntonio36,

Sorry for the extremely late reply. You're right about this issue. I will try to fix it when I have time. :)

**Comment by tkue** [comment]
@Ntonio36,

Thanks for bringing up this issue - I would've assumed it was pulling all players if you hadn't. When I just counted, I got about 20K (the number should be lower since the last page probably doesn't have 48 players):

gold=99
silver=198
bronze=121
pagesize=48
pagesize * (gold + silver + bronze)
20064

If we wanted to pull all players, would we also need any other categories (Icons, etc.)? 

Also, do you know how to get an official count? I'm not sure how accurate futhead is and I don't see any easy way to get any official counts from EA.

**Comment by Ntonio36** [comment]
Hey @tkue.
To be fair, I'd personally expect Futhead to get full information from EA's database, so I don't believe there are "holes" or missing parts in their player catalog. I might be wrong, though, but if they really are the player database they claim being... There must not be any missing players out there at Futhead, so I'd personally consider them 100% complete.
Icons and other In-Forms are listed under their respective quality sections (>=75 ovr IFs are in Gold, >= 64 are in silver, etc. etc.), so it's definitely straightforward and definitely easy to completely pull all players.... or so I hope. But for your last question, I don't quite know if that's possible, knowing how silent EA is on many aspects of the game.
